apiVersion: v1
kind: Service
metadata:
    name: "hqazinfdevk8clu01-9b63"
    labels:
        app: "hqazinfdevk8clu01-9b63"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "hqazinfdevk8clu01-9b63"