on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: infdev.azurecr.io
        username: ${{ secrets.acr_infdev_username }}
        password: ${{ secrets.acr_infdev_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/vendor/github.com/hpcloud/tail" -f  "vendor/github.com/hpcloud/tail/Dockerfile" -t infdev.azurecr.io/hqazinfdevk8clu01:${{ github.sha }}
        docker push infdev.azurecr.io/hqazinfdevk8clu01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_hqazinfdevk8clu01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep hqazinfdevk8clu0110f1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace hqazinfdevk8clu0110f1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: hqazinfdevk8clu0110f1
        container-registry-url: infdev.azurecr.io
        container-registry-username: ${{ secrets.acr_infdev_username }}
        container-registry-password: ${{ secrets.acr_infdev_password }}
        secret-name: hqazinfdevk8dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: hqazinfdevk8clu0110f1
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          infdev.azurecr.io/hqazinfdevk8clu01:${{ github.sha }}
        imagepullsecrets: |
          hqazinfdevk8dockerauth